import { Dimensions } from "react-native";
import { loadAsync, useFonts } from 'expo-font';

export const screenDimensions = {
    // App dimensions
    windowWidth: Dimensions.get("window").width,
    windowHeight: Dimensions.get("window").height
};

export const globalFontSizes = {
    largeTitle: 50,
    h1: 30,
    h2: 22,
    h3: 20,
    h4: 18,
    h5: 16,
    h6: 14,
    h7: 13,
    h8: 12,
    h9: 11,
    h10: 10,
    body1: 30,
    body2: 20,
    body3: 16,
    body4: 14,
    body5: 12,
    body6: 11,
    body7: 10,
    body8: 9,
    body9: 8,
    body10: 7,
}

export const globalCustomizedFonts = {
    Lato: require("../assets/fonts/Lato-Medium.ttf"),
}

export const globalColors = {
    // Colors
    black: "#000000",
    brightBlack: "#1E1F20",
    charcoalBlack: "#36454F",
    jetBlack: "#343434",
    licorineBlack: "#1B1212",
    matteBlack: "#28282B",
    onyxBlack: "#353935",
    white: "#FFFFFF",
    alabasterWhite: "#EDEADE",
    boneWhite: "#F9F6EE",
    offWhite: "#FAF9F6",
    seashellWhite: "#FFF5EE",
    lightGray1: "#F5F5F6",
    lightGray2: "#C0C0C0",
    lightGray3: "#708090",
    lightGray4: "#818589",
    darkGray1: "#898C95",
    brightBlue: "#0096FF",
    neonBlue: "#1F51FF",
    cornflowerBlue: "#6495ED",
    slightBlue: "#CCFFFD",
    turquoiseBlue: "#40E0D0",
    skyBlue: "#87CEEB",
    steelBlue: "#4682B4",
    sapphireBlue: "#0F52BA",
    aquamarineGreen: "#7FFFD4",
    armyGreen: "#454B1B",
    blueGreen: "#088F8F",
    cadmiumGreen: "#097969",
    brightGreen: "#AAFF00",
    forestGreen: "#228B22",
    grassGreen: "#7CFC00",
    jadeGreen: "#00A36C",
    lightGreen: "#90EE90",
    limeGreen: "#32CD32",
    malachiteGreen: "#0BDA51",
    mintGreen: "#98FB98",
    neonGreen: "#0FFF50",
    springGreen: "#00FF7F",
    tealGreen: "#008080",
    amberOrange: "#FFBF00",
    apricotOrange: "#FBCEB1",
    brightOrange: "#FFAC1C",
    neonOrange: "#FF5F1F",
    persimmonOrange: "#EC5800",
    tangerineOrange: "#F08000",
    bronzeOrange: "#FFAC1C",
    brightYellow: "#FFEA00",
    chartreuseYellow: "#DFFF00",
    cadmiumYellow: "#FDDA0D",
    creamYellow: "#FFFDD0",
    goldenYellow: "#FFC000",
    icterineYellow: "#FCF55F",
    lemonYellow: "#FAFA33",
    maizeYellow: "#FBEC5D",
    mustardYellow: "#FFDB58",
    peachYellow: "#FFE5B4",
    saffronYellow: "#F4C430",
    vanilaYellow: "#F3E5AB",
    bloodRed: "#880808",
    brickRed: "#AA4A44",
    brightRed: "#EE4B2B",
    cadmiumRed: "#D22B2B",
    carmineRed: "#C41E3A",
    cherryRed: "#D2042D",
    mahoganyRed: "#C04000",
    neonRed: "#FF3131",
    persimmonRed: "#EC5800",
    rubyRed: "#E0115F",
    scarletRed: "#FF2400",
    siennaBrown: "#A0522D",
    amaranthPink: "#9F2B68",
    cerisePink: "#DE3163",
    coralPink: "#F88379",
    darkPink: "#AA336A",
    fuchsiaPink: "#FF00FF",
    hotPink: "#FF69B4",
    lightPink: "#FFB6C1",
    magentaPink: "#FF00FF",
    millennialPink: "#F3CFC6",
    neonPink: "#FF10F0",
    pastelPink: "#F8C8DC",
    plumPink: "#673147",
    raspberryPink: "#E30B5C",
    rosePink: "#F33A6A",
    thistlePink: "#D8BFD8",
    watermelonPink: "#E37383",
    purple: "#800080",
    brightPurple: "#BF40BF",
    byzantiumPurple: "#702963",
    irisPurple: "#5D3FD3",
    lightPurple: "#CBC3E3",
    mauvePurple: "#E0B0FF",
    orchidPurple: "#DA70D6",
    redPurple: "#953553",
    wisteriaPurple: "#BDB5D5",
    violet: "#7F00FF",

    transparent: "transparent",
    transparentWhite: "#00FFFFFF",
    transparentBlack: "#66000000",
}

export const globalFontStyles = {
    largeTitle: { fontFamily: "Roboto-regular", fontSize: globalFontSizes.largeTitle, lineHeight: 55},
    h1: { fontFamily: "Roboto-Black", fontSize: globalFontSizes.h1, lineHeight: 36 },
    h2: { fontFamily: "Roboto-Bold", fontSize: globalFontSizes.h2, lineHeight: 30 },
    h3: { fontFamily: "Roboto-Bold", fontSize: globalFontSizes.h3, lineHeight: 22 },
    h4: { fontFamily: "Roboto-Bold", fontSize: globalFontSizes.h4, lineHeight: 22 },
    body1: { fontFamily: "Roboto-Regular", fontSize: globalFontSizes.body1, lineHeight: 36 },
    body2: { fontFamily: "Roboto-Regular", fontSize: globalFontSizes.body2, lineHeight: 30 },
    body3: { fontFamily: "Roboto-Regular", fontSize: globalFontSizes.body3, lineHeight: 22 },
    body4: { fontFamily: "Roboto-Regular", fontSize: globalFontSizes.body4, lineHeight: 22 },
    body5: { fontFamily: "Roboto-Regular", fontSize: globalFontSizes.body5, lineHeight: 21 },
    body6: { fontFamily: "Roboto-Regular", fontSize: globalFontSizes.body6, lineHeight: 19 },
};

const Themes = { globalColors, globalFontStyles, screenDimensions, globalFontSizes, globalCustomizedFonts };

export default Themes;
